### ISSUE TITLE
Твой ментор

### ISSUE THREAD

**Issue by vanzoneway** [Artiomsin/Java-Algorithms#3]
1. Добавь в Reviewers Ирину Геннадьевну и меня 
2. .gitignore настрой должным образом ( убрать .target, .idea )
3. убрать pom.xml из каждой точки входа в программу ( т.е ты скорее всего брал, каждый раз создавал новый проект, зачем-то копировал в другую папку, в которой у тебя гит и пушил ). А должно быть так: делаешь проект, настраиваешь .gitignore, создаешь ветку ( там выполняешь задания ), заливаешь на гит и делаешь pull request. Условно task1.3 -> task_13 -> твои классы и Main; task_21 -> твои классы и Main и так далее.
4. как сделаешь все выше, в readme сделай ссылку на каждый раздел с заданиями ( для удобной навигации )
5. не делай много коммитов, один раздел сделал -> делаешь коммит. далее я смотрю, что нужно поменять -> ты меняешь, ты коммитишь. поэтому 
6. выполни все условия и я начну проверять, не сделаешь - не буду. этот пулл реквест чисто случайно увидел

**Comment by Artiomsin** [comment]
Почему то ваш аккаунт не находится в Reviewers
